version: "3"
services:
  rundeck:
    image: rundeck/rundeck:4.6.0
    ports:
      - 4440:4440
    environment:
      RUNDECK_GRAILS_URL: http://localhost
      RUNDECK_SERVER_FORWARDED: "true"
  apache:
    image: httpd:latest
    volumes:
      - ./config/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    ports:
    - 80:80